/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "tertiary": "#5c5b66",
        "surface-variant": "#e3e1e8",
        "tertiary-container": "#75737f",
        "background": "#faf8ff",
        "inverse-on-surface": "#f2f0f7",
        "inverse-primary": "#c6c0ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#fffbff",
        "surface-bright": "#faf8ff",
        "on-primary-fixed": "#150066",
        "on-tertiary-fixed-variant": "#464650",
        "secondary-fixed-dim": "#ffb0ca",
        "on-error": "#ffffff",
        "surface": "#faf8ff",
        "surface-container": "#efedf4",
        "secondary-container": "#feadc8",
        "surface-dim": "#dbd9e0",
        "primary-fixed": "#e4dfff",
        "outline": "#787585",
        "on-secondary-container": "#7a3d54",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c7c5d1",
        "outline-variant": "#c8c4d6",
        "secondary-fixed": "#ffd9e3",
        "primary-fixed-dim": "#c6c0ff",
        "on-error-container": "#93000a",
        "primary-container": "#6e60e8",
        "on-tertiary-fixed": "#1b1b24",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5748d0",
        "on-tertiary-container": "#fffbff",
        "secondary": "#8b4a62",
        "on-secondary": "#ffffff",
        "on-background": "#1a1b20",
        "on-surface": "#1a1b20",
        "on-primary-fixed-variant": "#3f2bb8",
        "on-secondary-fixed": "#39071f",
        "on-surface-variant": "#474554",
        "surface-container-low": "#f4f3fa",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e3e1e8",
        "surface-container-high": "#e9e7ee",
        "inverse-surface": "#2f3035",
        "tertiary-fixed": "#e4e1ee",
        "primary": "#5545ce",
        "on-secondary-fixed-variant": "#6f334a",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      boxShadow: {
        "ambient": "0 20px 40px rgba(123, 110, 246, 0.08)",
        "ambient-sm": "0 8px 20px rgba(123, 110, 246, 0.04)",
        "ambient-lg": "0 20px 40px rgba(123, 110, 246, 0.15)",
        "primary-glow": "0 10px 30px rgba(123, 110, 246, 0.3)",
      },
      keyframes: {
        "soft-pulse": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.8" },
          "50%": { transform: "scale(1.05)", opacity: "1" },
        },
        "loading": {
          "0%": { transform: "translateX(-100%)", width: "30%" },
          "50%": { width: "60%" },
          "100%": { transform: "translateX(250%)", width: "30%" },
        },
      },
      animation: {
        "soft-pulse": "soft-pulse 4s ease-in-out infinite",
        "loading": "loading 2s ease-in-out infinite",
        "spin-slow": "spin 10s linear infinite",
      },
    },
  },
  plugins: [],
}
